title: Cairo Housing Authority
email: falkreon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for the Cairo Housing Authority
baseurl: "/info_1500_project" # the subpath of your site, e.g. /blog
url: "https://falkreon.github.io/"
github_username:  falkreon

# Build settings
theme: 
plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
